services:
  backend:
    build: ./server
    volumes:
      - ./server:/app
      - backend_static:/app/static
    env_file:
      - .env
    restart: always

  frontend:
    build: ./client
    ports:
        - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  backend_static: